# Generated by Django 5.0.7 on 2024-07-25 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
