# Generated by Django 5.0.7 on 2024-07-25 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
