# Generated by Django 5.0.7 on 2024-07-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_pro_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/produto', verbose_name='Imagem de Capa'),
        ),
    ]
