# Generated by Django 5.0.7 on 2024-07-26 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cafes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cafes',
            new_name='cafe',
        ),
    ]
