# Generated by Django 5.0.7 on 2024-07-26 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_cafes_cafe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cafe',
        ),
    ]
