# Generated by Django 5.0.7 on 2024-07-26 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_cafe'),
    ]

    operations = [
        migrations.CreateModel(
            name='cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caf_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('caf_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='preço')),
                ('caf_estoque', models.IntegerField(verbose_name='Quantidade em Estoque')),
                ('caf_image', models.ImageField(blank=True, null=True, upload_to='images/cafes', verbose_name='Imagem de Capa')),
                ('caf_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
